/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package View;

import Model.Gestiones.GestionDeMensajes;
import Controller.MAIN;
import java.util.Vector;

/**
 *
 * @author AleXRD
 */
public class LeerMensajes extends javax.swing.JDialog {
    String ci;
    Vector<String> mensajes=new Vector<String>();
    int index=0;
    int cnt=1;
    javax.swing.JLabel cntMensajes;
    javax.swing.JButton Mensajes;
    /**
     * Creates new form LeerMensajes
     */
    public LeerMensajes(java.awt.Frame parent, boolean modal,String ci,javax.swing.JLabel cntMensajes,javax.swing.JButton Mensajes) {
        super(parent, modal);
        initComponents();
        MAIN.InitVentana(this,562,451);
        this.ci =ci;
        this.cntMensajes = cntMensajes;
        this.Mensajes = Mensajes;
        
        try{
            mensajes = GestionDeMensajes.CargarDatos(ci);
        }
        catch(Exception ex){
            
        }
        CargarMensajes();
        
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        IZQ = new javax.swing.JButton();
        DER = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(51, 51, 51));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jScrollPane1.setBackground(new java.awt.Color(255, 255, 255));
        jScrollPane1.setForeground(new java.awt.Color(0, 0, 0));

        jTextArea1.setEditable(false);
        jTextArea1.setBackground(new java.awt.Color(255, 255, 255));
        jTextArea1.setColumns(20);
        jTextArea1.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        jTextArea1.setForeground(new java.awt.Color(0, 0, 0));
        jTextArea1.setRows(5);
        jTextArea1.setText("Fulanito se compro un lambo");
        jTextArea1.setFocusable(false);
        jScrollPane1.setViewportView(jTextArea1);

        jPanel2.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 30, 430, 330));

        IZQ.setBackground(new java.awt.Color(255, 255, 255));
        IZQ.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        IZQ.setForeground(new java.awt.Color(0, 0, 0));
        IZQ.setText("<");
        IZQ.setFocusPainted(false);
        IZQ.setFocusable(false);
        IZQ.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                IZQActionPerformed(evt);
            }
        });
        jPanel2.add(IZQ, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 120, 50, 110));

        DER.setBackground(new java.awt.Color(255, 255, 255));
        DER.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        DER.setForeground(new java.awt.Color(0, 0, 0));
        DER.setText(">");
        DER.setFocusPainted(false);
        DER.setFocusable(false);
        DER.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DERActionPerformed(evt);
            }
        });
        jPanel2.add(DER, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 130, 50, 110));

        jButton3.setBackground(new java.awt.Color(51, 51, 51));
        jButton3.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jButton3.setForeground(new java.awt.Color(255, 255, 255));
        jButton3.setText("Aceptar");
        jButton3.setToolTipText("");
        jButton3.setFocusPainted(false);
        jButton3.setFocusable(false);
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        jPanel2.add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 370, 130, -1));

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(18, 16, 530, 410));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 562, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 451, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
        GestionDeMensajes.BorrarMensaje(ci, cnt);
        MAIN.InitBottonMensajes(cntMensajes, Mensajes, ci);
        dispose();
    }//GEN-LAST:event_jButton3ActionPerformed

    private void DERActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DERActionPerformed
        // TODO add your handling code here:
        index++;
        cnt++;
        CargarMensajes();
    }//GEN-LAST:event_DERActionPerformed

    private void IZQActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_IZQActionPerformed
        // TODO add your handling code here:
        index--;
        CargarMensajes();
    }//GEN-LAST:event_IZQActionPerformed
    
    
    public void CargarMensajes(){
        if(mensajes.size()!=0)
            jTextArea1.setText(mensajes.get(index));
        else
            jTextArea1.setText("");
        //Controlar botones
        if(index==0){
            IZQ.setEnabled(false);
        }
        else{
            IZQ.setEnabled(true);
        }
        if(index==mensajes.size()-1){
            DER.setEnabled(false);
        }
        else{
            DER.setEnabled(true);
        }
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(LeerMensajes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(LeerMensajes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(LeerMensajes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(LeerMensajes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        /*java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                LeerMensajes dialog = new LeerMensajes(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                    }
                });
                dialog.setVisible(true);
            }
        });*/
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton DER;
    private javax.swing.JButton IZQ;
    private javax.swing.JButton jButton3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea jTextArea1;
    // End of variables declaration//GEN-END:variables
}
