/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package View;

import Controller.Empresa;
import Model.GestionDeCuentas;
import Model.Usuario;
import Model.Persona;
import Model.Cliente;

/**
 *
 * @author AleXRD
 */
public class SesionClient extends javax.swing.JFrame {
    Cliente current ;
    /**
     * Creates new form SesionClient
     */
    public SesionClient(Usuario user) {
        initComponents();
        current = new Cliente(user);
        ActualizarInfo();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        precio = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        Cantd = new javax.swing.JLabel();
        jButton2 = new javax.swing.JButton();
        NombreUsuario = new javax.swing.JLabel();
        Dinero1 = new javax.swing.JLabel();
        jButton4 = new javax.swing.JButton();
        Error = new javax.swing.JLabel();
        jButton3 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(51, 51, 51));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        precio.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        precio.setForeground(new java.awt.Color(0, 0, 0));
        precio.setText("50$");
        jPanel2.add(precio, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 210, 80, 60));

        jButton1.setBackground(new java.awt.Color(51, 51, 51));
        jButton1.setForeground(new java.awt.Color(255, 255, 255));
        jButton1.setText("Ver Sesiones");
        jButton1.setFocusPainted(false);
        jPanel2.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 80, 140, 30));

        Cantd.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        Cantd.setForeground(new java.awt.Color(0, 0, 0));
        jPanel2.add(Cantd, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 20, 210, 40));

        jButton2.setBackground(new java.awt.Color(51, 51, 51));
        jButton2.setForeground(new java.awt.Color(255, 255, 255));
        jButton2.setText("PedirServicio");
        jButton2.setFocusPainted(false);
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jPanel2.add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 210, 140, 60));

        NombreUsuario.setBackground(new java.awt.Color(51, 51, 51));
        NombreUsuario.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        NombreUsuario.setForeground(new java.awt.Color(0, 0, 0));
        NombreUsuario.setText("NombreUsuario");
        NombreUsuario.setFocusable(false);
        jPanel2.add(NombreUsuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 20, 310, 40));

        Dinero1.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        Dinero1.setForeground(new java.awt.Color(0, 0, 0));
        Dinero1.setText("Dinero:");
        jPanel2.add(Dinero1, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 20, -1, 40));

        jButton4.setBackground(new java.awt.Color(51, 51, 51));
        jButton4.setForeground(new java.awt.Color(255, 255, 255));
        jButton4.setText("Ingresar Dinero");
        jButton4.setFocusPainted(false);
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        jPanel2.add(jButton4, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 80, 170, 30));

        Error.setBackground(new java.awt.Color(51, 51, 51));
        Error.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        Error.setForeground(new java.awt.Color(153, 0, 51));
        Error.setFocusable(false);
        jPanel2.add(Error, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 220, 310, 40));

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 60, 600, 290));

        jButton3.setBackground(new java.awt.Color(51, 51, 51));
        jButton3.setForeground(new java.awt.Color(255, 255, 255));
        jButton3.setText("X");
        jButton3.setFocusPainted(false);
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(660, 10, 50, 50));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 720, 390));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Portal().setVisible(true);
            }
        });
        dispose();
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        try{
        current.PedirServicio();
        ActualizarInfo();
        }
        catch(Exception ex){
            Error.setText(ex.getMessage());
        }
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        // TODO add your handling code here:
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                GestionarDinero dialog = new GestionarDinero(new javax.swing.JFrame(),Cantd, true,current.getUsuario());
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        ActualizarUser();
                    }
                });
                
                
                dialog.setVisible(true);
            }
        });
    }//GEN-LAST:event_jButton4ActionPerformed
    public void ActualizarUser(){
        Usuario user =GestionDeCuentas.BuscarUsuario(current);
        current = new Cliente(user);
        System.out.println(current.getDinero());
        ActualizarInfo();
    }
    public void ActualizarInfo(){
        NombreUsuario.setText(current.getNombre());
        precio.setText(String.valueOf(Empresa.coste)+"$");
        String cantidad = String.valueOf(current.getDinero()+"$");
        Cantd.setText(cantidad);
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(SesionClient.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(SesionClient.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(SesionClient.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(SesionClient.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        /*java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new SesionClient().setVisible(true);
            }
        });*/
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Cantd;
    private javax.swing.JLabel Dinero1;
    private javax.swing.JLabel Error;
    private javax.swing.JLabel NombreUsuario;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JLabel precio;
    // End of variables declaration//GEN-END:variables
}
