/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package View;

import Controller.Empresa;
import Controller.MAIN;
import Model.Taxista;
import Model.Usuario;
import View.Acceso.VerSesiones;
import java.awt.Color;
import java.awt.Dimension;
import java.awt.Toolkit;
import javax.swing.JFrame;

/**
 *
 * @author AleXRD
 */
public class TaxistaMenu extends javax.swing.JFrame {
    Taxista current;
    int myPos;
    /**
     * Creates new form TaxistaMenu
     */
    public TaxistaMenu(Usuario user) {
        initComponents();
        Nombre.setText(user.getNombre());
        
        MAIN.Centrar(this);
        
        for(int i =0;i<Empresa.trabajadores.taxistas.size();i++){
            if(Empresa.trabajadores.taxistas.get(i).getCI().equals(user.getCI())){
                current = Empresa.trabajadores.taxistas.get(i);
                myPos=i;
            }
        }
        Cargar();
    }
    public void Cargar(){
        NombrePedido.setText("(Vacio)");
        Aceptar.setVisible(false);
        Negar.setVisible(false);
        Hecho.setVisible(false);
        NombrePedido.setForeground(Color.black);
        if(current.isTrabajando()==true){
            jRadioButton1.setSelected(true);
            EstaTrabajando();
        }
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        Nombre = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jRadioButton1 = new javax.swing.JRadioButton();
        jLabel1 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        NombrePedido = new javax.swing.JLabel();
        Negar = new javax.swing.JButton();
        Aceptar = new javax.swing.JButton();
        Hecho = new javax.swing.JButton();
        Error = new javax.swing.JLabel();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(51, 51, 51));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Nombre.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        Nombre.setForeground(new java.awt.Color(0, 0, 0));
        Nombre.setText("Nombre");
        jPanel2.add(Nombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 20, 120, 30));

        jButton1.setBackground(new java.awt.Color(51, 51, 51));
        jButton1.setForeground(new java.awt.Color(255, 255, 255));
        jButton1.setText("Ver Sesiones");
        jButton1.setFocusPainted(false);
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel2.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 20, 110, 30));

        jRadioButton1.setBackground(new java.awt.Color(51, 51, 51));
        jRadioButton1.setForeground(new java.awt.Color(255, 255, 255));
        jRadioButton1.setText("Trabajando");
        jRadioButton1.setFocusPainted(false);
        jRadioButton1.setFocusable(false);
        jRadioButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton1ActionPerformed(evt);
            }
        });
        jPanel2.add(jRadioButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 20, 140, -1));

        jLabel1.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 0, 0));
        jLabel1.setText("Pedido:");
        jPanel2.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 80, 80, 30));

        jPanel3.setBackground(new java.awt.Color(255, 255, 255));
        jPanel3.setBorder(javax.swing.BorderFactory.createMatteBorder(2, 2, 2, 2, new java.awt.Color(0, 0, 0)));
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        NombrePedido.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        NombrePedido.setForeground(new java.awt.Color(0, 0, 0));
        NombrePedido.setText("Nombre Pedido");
        jPanel3.add(NombrePedido, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 270, 50));

        Negar.setBackground(new java.awt.Color(51, 51, 51));
        Negar.setForeground(new java.awt.Color(204, 0, 0));
        Negar.setText("Negar");
        Negar.setFocusPainted(false);
        Negar.setFocusable(false);
        Negar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                NegarActionPerformed(evt);
            }
        });
        jPanel3.add(Negar, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 10, 80, 50));

        Aceptar.setBackground(new java.awt.Color(51, 51, 51));
        Aceptar.setForeground(new java.awt.Color(0, 255, 0));
        Aceptar.setText("Aceptar");
        Aceptar.setFocusPainted(false);
        Aceptar.setFocusable(false);
        Aceptar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AceptarActionPerformed(evt);
            }
        });
        jPanel3.add(Aceptar, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 10, 80, 50));

        Hecho.setBackground(new java.awt.Color(51, 51, 51));
        Hecho.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        Hecho.setForeground(new java.awt.Color(255, 255, 255));
        Hecho.setText("Hecho");
        Hecho.setFocusPainted(false);
        Hecho.setFocusable(false);
        Hecho.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                HechoActionPerformed(evt);
            }
        });
        jPanel3.add(Hecho, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 10, 150, 50));

        jPanel2.add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 110, 500, 70));

        Error.setForeground(new java.awt.Color(255, 0, 0));
        Error.setToolTipText("");
        Error.setBorder(javax.swing.BorderFactory.createMatteBorder(2, 2, 2, 2, new java.awt.Color(0, 0, 0)));
        jPanel2.add(Error, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 360, 400, 30));

        jButton2.setBackground(new java.awt.Color(51, 51, 51));
        jButton2.setFont(new java.awt.Font("Dialog", 1, 36)); // NOI18N
        jButton2.setForeground(new java.awt.Color(255, 255, 255));
        jButton2.setText("SOS");
        jButton2.setFocusPainted(false);
        jButton2.setFocusable(false);
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jPanel2.add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 319, 110, 71));

        jButton3.setBackground(new java.awt.Color(51, 51, 51));
        jButton3.setForeground(new java.awt.Color(255, 255, 255));
        jButton3.setText("Ver Mapa");
        jButton3.setFocusPainted(false);
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        jPanel2.add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 320, 110, 30));

        jButton4.setBackground(new java.awt.Color(51, 51, 51));
        jButton4.setForeground(new java.awt.Color(255, 255, 255));
        jButton4.setText("Ver Turnos");
        jButton4.setActionCommand("Ver Turnos");
        jButton4.setFocusPainted(false);
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        jPanel2.add(jButton4, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 20, 120, 30));

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 40, 540, 400));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 600, 480));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new VerSesiones().setVisible(true);
            }
        });
        dispose();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jRadioButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton1ActionPerformed
        // TODO add your handling code here:
        //Activar y Desactivar el boton de trabajo
        if(jRadioButton1.isSelected()){
            jRadioButton1.setForeground(new java.awt.Color(0, 255, 0));
            current.setTrabajando(true);
        }
        else{
            jRadioButton1.setForeground(new java.awt.Color(255, 255, 255));
            current.setTrabajando(false);
        }
    }//GEN-LAST:event_jRadioButton1ActionPerformed
    public void EstaTrabajando(){
        jRadioButton1.setForeground(new java.awt.Color(0, 255, 0));
        
        current.setTrabajando(true);
        if(current.getPedido()!=null){
            if(!current.getPedido().getCI().equals("")){    
                if(current.isPedidoAceptado()==false){
                NombrePedido.setText(current.getPedido().getNombre()+"- Direccion:"+current.getPedido().getDireccion());
                Aceptar.setVisible(true);
                Negar.setVisible(true);
                }
                else{
                Error.setText("Ha aceptado el pedido, asegurese de cumplir con el!");
                Aceptar.setVisible(false);
                Negar.setVisible(false);
                Hecho.setVisible(true);
                NombrePedido.setForeground(Color.green);
                NombrePedido.setText(current.getPedido().getNombre()+"- Direccion:"+current.getPedido().getDireccion());
                }
            }
        }
        
    }
    private void AceptarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AceptarActionPerformed
        // TODO add your handling code here:
        Error.setText("Ha aceptado el pedido, asegurese de cumplir con el!");
        Aceptar.setVisible(false);
        Negar.setVisible(false);
        Hecho.setVisible(true);
        current.setPedidoAceptado(true);
        NombrePedido.setForeground(Color.green);
    }//GEN-LAST:event_AceptarActionPerformed

    private void NegarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_NegarActionPerformed
        // TODO add your handling code here:
        Empresa.PedidoNegado(current.getPedido(), myPos);
        current.setPedido(new Usuario());
        Cargar();
    }//GEN-LAST:event_NegarActionPerformed

    private void HechoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_HechoActionPerformed
        // TODO add your handling code here:
        Error.setText("Buen Trabajo!");
        Error.setForeground(Color.green);
        current.setPedidoAceptado(false);
        current.setPedido(new Usuario());
        Cargar();
    }//GEN-LAST:event_HechoActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        if(current.isEnRescate()==false){
            jRadioButton1.setForeground(new java.awt.Color(255, 0, 0));
            jRadioButton1.setEnabled(false);
            current.setEnRescate(true);
            jButton2.setBackground(Color.red);
            Error.setText("Su mensaje de SOS ha sido enviado, resista.");
        }
        else{
            jRadioButton1.setEnabled(true);
            jRadioButton1.setForeground(new java.awt.Color(255, 255, 255));
            jButton2.setBackground(new java.awt.Color(51, 51, 51));
            current.setEnRescate(false);
            Error.setText("");
            Cargar();
        }
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        // TODO add your handling code here:
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                VerTurnos dialog = new VerTurnos(new javax.swing.JFrame(), true,current.getTurnos());
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        
                    }
                });
                dialog.setVisible(true);
            }
        });
    }//GEN-LAST:event_jButton4ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TaxistaMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TaxistaMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TaxistaMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TaxistaMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                //new TaxistaMenu().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Aceptar;
    private javax.swing.JLabel Error;
    private javax.swing.JButton Hecho;
    private javax.swing.JButton Negar;
    private javax.swing.JLabel Nombre;
    private javax.swing.JLabel NombrePedido;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JRadioButton jRadioButton1;
    // End of variables declaration//GEN-END:variables
}
