/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package View.Acceso;

import Controller.Empresa.Empresa;
import Controller.MAIN;
import Model.Gestiones.GestionDeCuentas;
import Model.Personal.Usuario;
import View.Trabajadores.OperadorMenu;
import View.Cliente.SesionClient;
import java.util.Vector;

/**
 *
 * @author AleXRD
 */
public class VerSesiones extends javax.swing.JFrame {
    Vector<Usuario> users;
    
    /**
     * Creates new form VerSesiones
     */
    public VerSesiones() {
        initComponents();
        MAIN.Centrar(this);
        users = GestionDeCuentas.mySesions;
        
            segundo.setVisible(false);
            tercero.setVisible(false);
        completeCelds(users.size());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        primer = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        exit1 = new javax.swing.JButton();
        segundo = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jButton2 = new javax.swing.JButton();
        exit2 = new javax.swing.JButton();
        tercero = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jButton3 = new javax.swing.JButton();
        exit3 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(51, 51, 51));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        primer.setBackground(new java.awt.Color(255, 255, 255));
        primer.setBorder(javax.swing.BorderFactory.createMatteBorder(2, 2, 2, 2, new java.awt.Color(0, 0, 0)));
        primer.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 0, 0));
        jLabel1.setText("Fulanito");
        jLabel1.setToolTipText("");
        primer.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 0, 272, 60));

        jButton1.setBackground(new java.awt.Color(51, 51, 51));
        jButton1.setForeground(new java.awt.Color(255, 255, 255));
        jButton1.setFocusPainted(false);
        jButton1.setFocusable(false);
        primer.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 10, 150, 40));

        exit1.setBackground(new java.awt.Color(51, 51, 51));
        exit1.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        exit1.setForeground(new java.awt.Color(255, 255, 255));
        exit1.setText("X");
        exit1.setFocusPainted(false);
        exit1.setFocusable(false);
        exit1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                exit1ActionPerformed(evt);
            }
        });
        primer.add(exit1, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 10, 50, 40));

        jPanel2.add(primer, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 20, 520, 60));

        segundo.setBackground(new java.awt.Color(255, 255, 255));
        segundo.setBorder(javax.swing.BorderFactory.createMatteBorder(2, 2, 2, 2, new java.awt.Color(0, 0, 0)));
        segundo.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(0, 0, 0));
        jLabel2.setText("Fulanito");
        jLabel2.setToolTipText("");
        segundo.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 0, 272, 60));

        jButton2.setBackground(new java.awt.Color(51, 51, 51));
        jButton2.setForeground(new java.awt.Color(255, 255, 255));
        jButton2.setToolTipText("");
        jButton2.setFocusPainted(false);
        jButton2.setFocusable(false);
        segundo.add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 10, 150, 40));

        exit2.setBackground(new java.awt.Color(51, 51, 51));
        exit2.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        exit2.setForeground(new java.awt.Color(255, 255, 255));
        exit2.setText("X");
        exit2.setFocusPainted(false);
        exit2.setFocusable(false);
        segundo.add(exit2, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 10, 50, 40));

        jPanel2.add(segundo, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 90, 520, -1));

        tercero.setBackground(new java.awt.Color(255, 255, 255));
        tercero.setBorder(javax.swing.BorderFactory.createMatteBorder(2, 2, 2, 2, new java.awt.Color(0, 0, 0)));
        tercero.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel3.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(0, 0, 0));
        jLabel3.setText("Fulanito");
        jLabel3.setToolTipText("");
        tercero.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 0, 272, 60));

        jButton3.setBackground(new java.awt.Color(51, 51, 51));
        jButton3.setForeground(new java.awt.Color(255, 255, 255));
        jButton3.setFocusPainted(false);
        jButton3.setFocusable(false);
        tercero.add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 10, 150, 40));

        exit3.setBackground(new java.awt.Color(51, 51, 51));
        exit3.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        exit3.setForeground(new java.awt.Color(255, 255, 255));
        exit3.setText("X");
        exit3.setFocusPainted(false);
        exit3.setFocusable(false);
        tercero.add(exit3, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 10, 50, 40));

        jPanel2.add(tercero, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 160, 520, -1));

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 30, 560, 250));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 616, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 317, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void exit1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_exit1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_exit1ActionPerformed
    
    private void completeCelds(int o){
        if(o>=1){
            jLabel1.setText(users.get(0).getNombre()+"("+users.get(0).getType()+")");
            jButton1.setText("Abrir Sesion");
            exit1.addActionListener(new java.awt.event.ActionListener() {
                public void actionPerformed(java.awt.event.ActionEvent evt) {
                    buttonBorrar(0);
                }
            });
            jButton1.addActionListener(new java.awt.event.ActionListener() {
                public void actionPerformed(java.awt.event.ActionEvent evt) {
                    AbrirSesion(users.get(0));
                }
            });
            
            
            segundo.setVisible(true);
            jLabel2.setText("Vacio.");
            jButton2.setText("Iniciar Sesion");
            jButton2.addActionListener(new java.awt.event.ActionListener() {
                public void actionPerformed(java.awt.event.ActionEvent evt) {
                    buttonIniciarSesion();
                }
            });
            exit2.setVisible(false);
        }
        else{
            jLabel1.setText("Vacio.");
            jButton1.setText("Iniciar Sesion");
            exit1.setVisible(false);
            jButton1.addActionListener(new java.awt.event.ActionListener() {
                public void actionPerformed(java.awt.event.ActionEvent evt) {
                    buttonIniciarSesion();
                }
            });
        }
        
        if(o>=2){
            jLabel2.setText(users.get(1).getNombre()+"("+users.get(1).getType()+")");
            exit2.setVisible(true);
            exit2.addActionListener(new java.awt.event.ActionListener() {
                public void actionPerformed(java.awt.event.ActionEvent evt) {
                    buttonBorrar(1);
                }
            });
            //Cambiar boton
            jButton2.setVisible(false);
            jButton2 = new javax.swing.JButton();
            jButton2.setBackground(new java.awt.Color(51, 51, 51));
            jButton2.setForeground(new java.awt.Color(255, 255, 255));
            jButton2.setToolTipText("");
            jButton2.setText("Abrir Sesion");
            jButton2.setFocusPainted(false);
            jButton2.setFocusable(false);
            segundo.add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 10, 150, 40));
            jButton2.addActionListener(new java.awt.event.ActionListener() {
                public void actionPerformed(java.awt.event.ActionEvent evt) {
                    AbrirSesion(users.get(1));
                }
            });
            
            
            tercero.setVisible(true);
            jLabel3.setText("Vacio.");
            jButton3.setText("Iniciar Sesion");
            jButton3.addActionListener(new java.awt.event.ActionListener() {
                public void actionPerformed(java.awt.event.ActionEvent evt) {
                    buttonIniciarSesion();
                }
            });
            exit3.setVisible(false);
        }
        if(o==3){
            jLabel3.setText(users.get(2).getNombre()+"("+users.get(2).getType()+")");
            jButton3.setText("Abrir Sesion");
            exit3.setVisible(true);
            exit3.addActionListener(new java.awt.event.ActionListener() {
                public void actionPerformed(java.awt.event.ActionEvent evt) {
                    buttonBorrar(2);
                }
            });
            //Cambiar boton
            jButton3.setVisible(false);
            jButton3 = new javax.swing.JButton();
            jButton3.setBackground(new java.awt.Color(51, 51, 51));
            jButton3.setForeground(new java.awt.Color(255, 255, 255));
            jButton3.setToolTipText("");
            jButton3.setText("Abrir Sesion");
            jButton3.setFocusPainted(false);
            jButton3.setFocusable(false);
            tercero.add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 10, 150, 40));
            jButton3.addActionListener(new java.awt.event.ActionListener() {
                public void actionPerformed(java.awt.event.ActionEvent evt) {
                    AbrirSesion(users.get(2));
                }
            });
            
            
        }
    }
    public void AbrirSesion(Usuario user){
        Empresa.IniciarSesion(user);
        dispose();
    }
    public void buttonBorrar(int pos){
            users.remove(pos);
            java.awt.EventQueue.invokeLater(new Runnable() {
                public void run() {
                    new VerSesiones().setVisible(true);
                }
            });  
            dispose();
    }
    public void buttonIniciarSesion(){
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Portal().setVisible(true);
            }
        });
        dispose();
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(VerSesiones.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(VerSesiones.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(VerSesiones.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(VerSesiones.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new VerSesiones().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton exit1;
    private javax.swing.JButton exit2;
    private javax.swing.JButton exit3;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel primer;
    private javax.swing.JPanel segundo;
    private javax.swing.JPanel tercero;
    // End of variables declaration//GEN-END:variables
}
