/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package View.Trabajadores;

import Controller.Empresa.Empresa;
import Controller.MAIN;
import Controller.Empresa.Pedido;
import Model.Personal.Cliente;
import Model.Personal.Operador;
import Model.Personal.Taxista;
import Model.Personal.Usuario;
import View.Acceso.VerSesiones;
import View.LeerMensajes;
import java.awt.Color;
import java.io.IOException;
import java.util.Vector;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JComboBox;

/**
 *
 * @author AleXRD
 */
public class OperadorMenu extends javax.swing.JFrame {
    
    public String[] nombres;
    int cant;
    Operador current;
    int myPos;
    /**
     * Creates new form OperadorMenu
     */
    public OperadorMenu(Usuario user) {
        initComponents();
        MAIN.InitVentana(this,689,414);
        
        for(int i =0;i<Empresa.trabajadores.operadores.size();i++){
            if(Empresa.trabajadores.operadores.get(i).getCI().equals(user.getCI())){
                current = Empresa.trabajadores.operadores.get(i);
                myPos=i;
            }
        }
        
        jLabel1.setText(current.getNombre());
        try {
            current.CargarBilletera();
        } catch (Exception ex) {
            Error.setText(ex.getMessage());
        } 
        jLabel2.setText(String.valueOf(current.getBilletera().getDinero())+"$");
        
        //Recoger nombres de taxistas
        Vector<Taxista> taxistas =Empresa.trabajadores.taxistas;
        nombres = new String[taxistas.size()];
        for(int i =0;i<taxistas.size();i++){
            nombres[i] =taxistas.get(i).getNombre();
        }
        MAIN.InitBottonMensajes(cntMensajes,Mensajes,current.getCI());
    }


    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jRadioButton1 = new javax.swing.JRadioButton();
        jButton1 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        Error = new javax.swing.JLabel();
        jButton4 = new javax.swing.JButton();
        cntMensajes = new javax.swing.JLabel();
        Mensajes = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(51, 51, 51));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jRadioButton1.setBackground(new java.awt.Color(51, 51, 51));
        jRadioButton1.setForeground(new java.awt.Color(255, 255, 255));
        jRadioButton1.setText("Trabajando");
        jRadioButton1.setFocusPainted(false);
        jRadioButton1.setFocusable(false);
        jRadioButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton1ActionPerformed(evt);
            }
        });
        jPanel2.add(jRadioButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 20, 140, -1));

        jButton1.setBackground(new java.awt.Color(51, 51, 51));
        jButton1.setForeground(new java.awt.Color(255, 255, 255));
        jButton1.setText("Ver Sesiones");
        jButton1.setFocusPainted(false);
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel2.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 20, 120, 30));

        jLabel1.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 0, 0));
        jLabel1.setText("Nombre");
        jPanel2.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 20, 130, 30));

        Error.setForeground(new java.awt.Color(153, 0, 0));
        jPanel2.add(Error, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 326, 470, 20));

        jButton4.setBackground(new java.awt.Color(51, 51, 51));
        jButton4.setForeground(new java.awt.Color(255, 255, 255));
        jButton4.setText("Ver Turnos");
        jButton4.setFocusPainted(false);
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        jPanel2.add(jButton4, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 20, 120, 30));

        cntMensajes.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        cntMensajes.setForeground(new java.awt.Color(0, 0, 0));
        cntMensajes.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        cntMensajes.setText("0");
        jPanel2.add(cntMensajes, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 40, 40, 30));

        Mensajes.setBackground(new java.awt.Color(51, 51, 51));
        Mensajes.setForeground(new java.awt.Color(255, 255, 255));
        Mensajes.setText("!");
        Mensajes.setToolTipText("");
        Mensajes.setFocusPainted(false);
        Mensajes.setFocusable(false);
        Mensajes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MensajesActionPerformed(evt);
            }
        });
        jPanel2.add(Mensajes, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 10, 40, 40));

        jLabel2.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(0, 0, 0));
        jPanel2.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 40, 80, 30));

        jLabel3.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(0, 0, 0));
        jLabel3.setText("Dinero: ");
        jPanel2.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 40, 70, 30));

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 30, 630, 350));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 689, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 414, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jRadioButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton1ActionPerformed
        // TODO add your handling code here:
        //Activar y Desactivar el boton de trabajo
        if(jRadioButton1.isSelected()){
            jRadioButton1.setForeground(new java.awt.Color(0, 255, 0));
            Vector<Pedido> pedidos = Empresa.pedidos;
            for(int i=0;cant<3&&i<pedidos.size();i++){
                if(pedidos.get(i).enProceso==false){
                    CrearPedido(cant,pedidos.get(i));
                    cant++;
                }
                else
                    continue;
            }
            
        }
        else{
            jRadioButton1.setForeground(new java.awt.Color(255, 255, 255));
            while(cant>=1){
                jPanel2.remove(9);
                cant--;
            }
            
            jPanel2.repaint();
        }
    }//GEN-LAST:event_jRadioButton1ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new VerSesiones().setVisible(true);
            }
        });
        dispose();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        // TODO add your handling code here:
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                VerTurnos dialog = new VerTurnos(new javax.swing.JFrame(), true,current.getTurnos());
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {

                    }
                });
                dialog.setVisible(true);
            }
        });
    }//GEN-LAST:event_jButton4ActionPerformed

    private void MensajesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MensajesActionPerformed
        // TODO add your handling code here:
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                LeerMensajes dialog = new LeerMensajes(new javax.swing.JFrame(), true,current.getCI(),cntMensajes,Mensajes);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                    }
                });
                dialog.setVisible(true);
            }
        });
    }//GEN-LAST:event_MensajesActionPerformed
    
    //Crear un boton por pedido
    public void CrearPedido(int posY,Pedido pedido){             
        javax.swing.JPanel jPanel3;         
        javax.swing.JButton jButton2;
        javax.swing.JComboBox<String> jComboBox1;
        javax.swing.JLabel jLabel1;
         
        jPanel3 = new javax.swing.JPanel();
        jComboBox1 = new javax.swing.JComboBox<>();
        jLabel1 = new javax.swing.JLabel();
        jButton2 = new javax.swing.JButton();
        jPanel3.setBackground(new java.awt.Color(255, 255, 255));
        jPanel3.setBorder(javax.swing.BorderFactory.createMatteBorder(2, 2, 2, 2, new java.awt.Color(0, 0, 0)));
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setForeground(new java.awt.Color(0, 0, 0));
        jLabel1.setText(pedido.client.getNombre()+"-Direccion:"+pedido.client.getDireccion());
        jPanel3.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 0, 226, 70));

        jComboBox1.setBackground(new java.awt.Color(51, 51, 51));
                if(Empresa.trabajadores.taxistas.get(0).isTrabajando()==true){
                    jComboBox1.setForeground(Color.green);
                }
                else{
                    jComboBox1.setForeground(Color.red);
                }
        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(nombres));
        jComboBox1.setFocusable(false);
        jComboBox1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                if(Empresa.trabajadores.taxistas.get(jComboBox1.getSelectedIndex()).isTrabajando()==true){
                    jComboBox1.setForeground(Color.green);
                }
                else{
                    jComboBox1.setForeground(Color.red);
                }
            }
        });
        jPanel3.add(jComboBox1, new org.netbeans.lib.awtextra.AbsoluteConstraints(278, 20, 150, 30));

        jButton2.setBackground(new java.awt.Color(51, 51, 51));
        jButton2.setForeground(new java.awt.Color(255, 255, 255));
        jButton2.setText("Enviar Peticion");
        jButton2.setBorderPainted(false);
        jButton2.setFocusable(false);
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                try {
                    current.AsignarPedido(jComboBox1.getSelectedIndex(), pedido);
                    //Borrar
                    jPanel2.remove(9+posY);
                    //Empresa.pedidos.remove(posY);
                    cant--;
                    //ActualizarInterfaz
                    Actualizar();
                    //Repaint
                    jPanel2.repaint();
                } catch (Exception ex) {
                    Error.setText(ex.getMessage());
                }
            }
        });
        jPanel3.add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 10, 130, 50));

        jPanel2.add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 70+(posY*90), 580, 70));

        pack();
    }
    
    public void Actualizar(){
        while(cant>=1){
            jPanel2.remove(9);
            cant--;
        }   
        Vector<Pedido> pedidos = Empresa.pedidos;
        for(int i=0;cant<3&&i<pedidos.size();i++){
            if(pedidos.get(i).enProceso==false){
                CrearPedido(cant,pedidos.get(i));
                cant++;
            }
            else
                continue;
        }
            
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(OperadorMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(OperadorMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(OperadorMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(OperadorMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        /*java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new OperadorMenu().setVisible(true);
            }
        });*/
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Error;
    private javax.swing.JButton Mensajes;
    private javax.swing.JLabel cntMensajes;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton4;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JRadioButton jRadioButton1;
    // End of variables declaration//GEN-END:variables
}
